export type FaqTag = "home" | "pricing" | "gestoria" | "verifactu" | "historias";
export interface FaqItem { q: string; a: string; tags: FaqTag[] }

export const faq: FaqItem[] = [
  { q: "¿Qué es VERI*FACTU y por qué lo necesito?", tags: ["home", "pricing", "verifactu"],
    a: "Es el sistema de la AEAT que obliga a que tus facturas se registren de forma verificable. Con FactuIO cada factura sale ya firmada, encadenada y con su QR, sin que tengas que hacer nada." },
  { q: "¿Tengo que enviar cada factura a Hacienda al momento?", tags: ["verifactu"],
    a: "Depende de la modalidad. En VERI*FACTU sí, se remite en el momento de facturar. En la modalidad no VERI*FACTU basta con conservar los registros íntegros y disponibles para que la AEAT pueda solicitarlos." },
  { q: "¿Puedo seguir usando Excel o Word para facturar?", tags: ["verifactu"],
    a: "No a partir de la fecha en que te obligue el calendario: los programas de facturación deben cumplir el RRSIF. Las facturas manuales en papel siguen permitidas en los casos que contempla la norma." },
  { q: "¿Qué pasa con las facturas anteriores a 2027?", tags: ["verifactu"],
    a: "No se regularizan retroactivamente. La obligación aplica a las facturas emitidas a partir de la fecha en que te corresponda cumplir." },
  { q: "¿Necesito certificado digital para VERI*FACTU?", tags: ["verifactu"],
    a: "No si delegas la firma en FactuIO: puedes emitir desde el primer día sin mover certificados." },
  { q: "¿Qué diferencia hay entre VERI*FACTU y la factura electrónica de la Ley Crea y Crece?", tags: ["verifactu"],
    a: "Son dos obligaciones distintas. VERI*FACTU regula cómo debe registrar y verificar tus facturas el software; la factura electrónica de la Ley Crea y Crece regula el formato de envío entre empresas y aún no tiene calendario definitivo." },
  { q: "¿Puedo cambiar de plan o cancelar cuando quiera?", tags: ["pricing"],
    a: "Sí. No hay permanencia: subes o bajas de plan desde tu cuenta y el cambio se aplica al siguiente ciclo. Si cancelas, conservas acceso de solo lectura a tus documentos." },
  { q: "¿Necesito certificado digital?", tags: ["home", "pricing"],
    a: "No. Puedes delegar la firma en FactuIO y emitir desde el primer día. Si tu gestoría firma por ti, también lo soportamos." },
  { q: "¿Qué pasa cuando termina la prueba gratuita?", tags: ["home", "pricing"],
    a: "Te avisamos antes de que acabe. Si no eliges plan, tu cuenta pasa a solo lectura: no perderás ninguna factura ni ningún dato." },
  { q: "Soy una gestoría, ¿cómo añado a mis clientes?", tags: ["pricing", "gestoria", "historias"],
    a: "Cada cliente es una empresa dentro de tu cuenta, con sus usuarios y permisos. Tú ves todo el porfolio; ellos, solo lo suyo. La firma delegada te permite emitir en su nombre con su autorización AEAT." },
  { q: "¿Puedo pasar las facturas y gastos a mi programa de contabilidad?", tags: ["gestoria"],
    a: "Sí. FactuIO exporta el enlace contable de A3 (SUENLACE.DAT) para ventas y compras desde la propia ficha de la empresa." },
  { q: "¿Funciona en el País Vasco (TicketBAI)?", tags: ["home"],
    a: "Sí. FactuIO genera y encadena los ficheros TicketBAI para Bizkaia, Gipuzkoa y Araba con el mismo flujo que VERI*FACTU." },
  { q: "¿Puedo empezar como autónomo y pasar a un plan con equipo más adelante?", tags: ["historias"],
    a: "Sí. Cambias de plan desde tu cuenta y se aplica al siguiente ciclo. Tus facturas, contactos y gastos se quedan donde están." },
  { q: "Mi gestoría ya usa FactuIO, ¿necesito mi propia cuenta?", tags: ["historias"],
    a: "No. Tu gestoría te invita por email, entras con tu móvil y ves solo tu empresa. Subes tickets y facturas desde la app y tu gestor se encarga del resto, sin coste adicional para ti." },
];
